modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="amaze" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
displayName="Amaze Mod" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="amaze-logo.png" #optional
credits="Created by Nathan Levy" #optional
authors="Nathan Levy" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This game will AMAZE you!

Swipe to move the ball and paint - you’ve got to color and paint your way across the AMAZE maze puzzles.

To fill in puzzles, fill each square to unlock more addictive AMAZE maze paint puzzles.
Watch out! AMAZE gets harder as you play, color and paint the maze, and fill in puzzles!
Painting the maze puzzles sounds easy, but you have to be super strategic to color and fill every square.

Make sure you fill in puzzles COMPLETELY! If you don’t fill even one square, you’re stuck in the paint maze FOREVER!
'''
[[dependencies.amaze]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.amaze]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
