package au.natelev.amaze.game;

import static au.natelev.amaze.game.LevelMaps1.*;
import static au.natelev.amaze.game.LevelMaps2.*;

public class LevelData {
    protected static int[][] getLevelMap(int i) {
        switch (i) {
            case 0:
                return levelMap0;
            case 1:
                return levelMap1;
            case 2:
                return levelMap2;
            case 3:
                return levelMap3;
            case 4:
                return levelMap4;
            case 5:
                return levelMap5;
            case 6:
                return levelMap6;
            case 7:
                return levelMap7;
            case 8:
                return levelMap8;
            case 9:
                return levelMap9;
            case 10:
                return levelMap10;
            case 11:
                return levelMap11;
            case 12:
                return levelMap12;
            case 13:
                return levelMap13;
            case 14:
                return levelMap14;
            case 15:
                return levelMap15;
            case 16:
                return levelMap16;
            case 17:
                return levelMap17;
            case 18:
                return levelMap18;
            case 19:
                return levelMap19;
            case 20:
                return levelMap20;
            case 21:
                return levelMap21;
            case 22:
                return levelMap22;
            case 23:
                return levelMap23;
            case 24:
                return levelMap24;
            case 25:
                return levelMap25;
            case 26:
                return levelMap26;
            case 27:
                return levelMap27;
            case 28:
                return levelMap28;
            case 29:
                return levelMap29;
            case 30:
                return levelMap30;
            case 31:
                return levelMap31;
            case 32:
                return levelMap32;
            case 33:
                return levelMap33;
            case 34:
                return levelMap34;
            case 35:
                return levelMap35;
            case 36:
                return levelMap36;
            case 37:
                return levelMap37;
            case 38:
                return levelMap38;
            case 39:
                return levelMap39;
            case 40:
                return levelMap40;
            case 41:
                return levelMap41;
            case 42:
                return levelMap42;
            case 43:
                return levelMap43;
            case 44:
                return levelMap44;
            case 45:
                return levelMap45;
            case 46:
                return levelMap46;
            case 47:
                return levelMap47;
            case 48:
                return levelMap48;
            case 49:
                return levelMap49;
            case 50:
                return levelMap50;
            case 51:
                return levelMap51;
            case 52:
                return levelMap52;
            case 53:
                return levelMap53;
            case 54:
                return levelMap54;
            case 55:
                return levelMap55;
            case 56:
                return levelMap56;
            case 57:
                return levelMap57;
            case 58:
                return levelMap58;
            case 59:
                return levelMap59;
            case 60:
                return levelMap60;
            case 61:
                return levelMap61;
            case 62:
                return levelMap62;
            case 63:
                return levelMap63;
            case 64:
                return levelMap64;
            case 65:
                return levelMap65;
            case 66:
                return levelMap66;
            case 67:
                return levelMap67;
            case 68:
                return levelMap68;
            case 69:
                return levelMap69;
            case 70:
                return levelMap70;
            case 71:
                return levelMap71;
            case 72:
                return levelMap72;
            case 73:
                return levelMap73;
            case 74:
                return levelMap74;
            case 75:
                return levelMap75;
            case 76:
                return levelMap76;
            case 77:
                return levelMap77;
            case 78:
                return levelMap78;
            case 79:
                return levelMap79;
            case 80:
                return levelMap80;
            case 81:
                return levelMap81;
            case 82:
                return levelMap82;
            case 83:
                return levelMap83;
            case 84:
                return levelMap84;
            case 85:
                return levelMap85;
            case 86:
                return levelMap86;
            case 87:
                return levelMap87;
            case 88:
                return levelMap88;
            case 89:
                return levelMap89;
            case 90:
                return levelMap90;
            case 91:
                return levelMap91;
            case 92:
                return levelMap92;
            case 93:
                return levelMap93;
            case 94:
                return levelMap94;
            case 95:
                return levelMap95;
            case 96:
                return levelMap96;
            case 97:
                return levelMap97;
            case 98:
                return levelMap98;
            case 99:
                return levelMap99;
            case 100:
                return levelMap100;
            case 101:
                return levelMap101;
            case 102:
                return levelMap102;
            case 103:
                return levelMap103;
        }
        return null;
    }

    protected static final int[][] levelMetadata = {
            {6, 6},
            {7, 7},
            {7, 7},
            {9, 9},
            {9, 8},
            {9, 8},
            {9, 8},
            {9, 8},
            {9, 9},
            {9, 10},
            {9, 11},
            {9, 10},
            {9, 10},
            {9, 10},
            {9, 10},
            {9, 10},
            {9, 13},
            {9, 12},
            {9, 12},
            {9, 14},
            {9, 14},
            {9, 12},
            {9, 12},
            {9, 9},
            {9, 9},
            {9, 9},
            {9, 9},
            {9, 9},
            {9, 9},
            {9, 9},
            {9, 12},
            {9, 12},
            {9, 12},
            {9, 11},
            {9, 10},
            {9, 11},
            {9, 11},
            {9, 11},
            {10, 12},
            {10, 12},
            {8, 14},
            {8, 14},
            {8, 14},
            {8, 13},
            {8, 13},
            {8, 14},
            {12, 12},
            {12, 12},
            {12, 12},
            {12, 12},
            {12, 14},
            {12, 14},
            {12, 14},
            {12, 14},
            {12, 14},
            {15, 15},
            {15, 15},
            {17, 15},
            {17, 15},
            {17, 15},
            {17, 16},
            {12, 12},
            {12, 12},
            {12, 12},
            {11, 12},
            {10, 12},
            {13, 12},
            {15, 20},
            {15, 15},
            {15, 15},
            {15, 15},
            {20, 15},
            {15, 15},
            {15, 15},
            {15, 15},
            {15, 15},
            {15, 15},
            {10, 15},
            {10, 15},
            {9, 13},
            {10, 10},
            {12, 12},
            {20, 12},
            {15, 17},
            {15, 15},
            {15, 15},
            {10, 10},
            {10, 15},
            {15, 15},
            {15, 15},
            {15, 15},
            {15, 15},
            {15, 15},
            {15, 15},
            {15, 15},
            {15, 20},
            {15, 20},
            {15, 20},
            {15, 10},
            {15, 10},
            {15, 10},
            {15, 15},
            {15, 15},
            {17, 16}
    };
}
